/* Puzzle bank. Each puzzle: four groups in difficulty order
   (yellow → green → blue → purple). Words are unique within a puzzle and
   every puzzle has exactly one valid solution. */
window.PUZZLES = [
  [
    ["Fruits", ["PEAR", "PLUM", "FIG", "MANGO"]],
    ["Tech giants", ["APPLE", "META", "ORACLE", "TESLA"]],
    ["Rivers", ["NILE", "THAMES", "SEINE", "DANUBE"]],
    ["___ball", ["FOOT", "BASKET", "SNOW", "EYE"]],
  ],
  [
    ["Dog breeds", ["BOXER", "POODLE", "BEAGLE", "HUSKY"]],
    ["Things with keys", ["PIANO", "KEYBOARD", "MAP", "LOCK"]],
    ["Chess pieces", ["KING", "QUEEN", "BISHOP", "ROOK"]],
    ["Boxing terms", ["JAB", "HOOK", "ROUND", "BELL"]],
  ],
  [
    ["Weather", ["RAIN", "SNOW", "HAIL", "FOG"]],
    ["Coffee orders", ["LATTE", "MOCHA", "ESPRESSO", "AMERICANO"]],
    ["Candy bars", ["MARS", "TWIX", "SNICKERS", "BOUNTY"]],
    ["Planets", ["VENUS", "SATURN", "JUPITER", "MERCURY"]],
  ],
  [
    ["Body parts", ["ARM", "LEG", "HIP", "TOE"]],
    ["Things you can break", ["FAST", "RECORD", "NEWS", "ICE"]],
    ["Units of time", ["SECOND", "MINUTE", "HOUR", "WEEK"]],
    ["___fish", ["STAR", "CAT", "GOLD", "SWORD"]],
  ],
  [
    ["Colors", ["RED", "BLUE", "PINK", "TEAL"]],
    ["Card games", ["POKER", "BRIDGE", "RUMMY", "HEARTS"]],
    ["Found in a bathroom", ["SINK", "TOWEL", "MIRROR", "TUB"]],
    ["Poker actions", ["FOLD", "CALL", "RAISE", "CHECK"]],
  ],
  [
    ["Vegetables", ["KALE", "LEEK", "BEET", "CORN"]],
    ["Music genres", ["ROCK", "JAZZ", "FOLK", "SOUL"]],
    ["Famous Michaels", ["JORDAN", "JACKSON", "PHELPS", "SCOTT"]],
    ["Dances", ["TANGO", "SALSA", "WALTZ", "SWING"]],
  ],
  [
    ["Farm animals", ["COW", "PIG", "HEN", "GOAT"]],
    ["Social apps", ["SNAP", "TIKTOK", "REDDIT", "DISCORD"]],
    ["___board", ["KEY", "SKATE", "SURF", "DASH"]],
    ["Camera terms", ["LENS", "FLASH", "ZOOM", "FOCUS"]],
  ],
  [
    ["Currencies", ["DOLLAR", "EURO", "YEN", "PESO"]],
    ["Superheroes", ["BATMAN", "FLASH", "THOR", "HULK"]],
    ["3D shapes", ["CUBE", "CONE", "PRISM", "SPHERE"]],
    ["___man", ["SNOW", "SPIDER", "IRON", "SAND"]],
  ],
  [
    ["Pizza toppings", ["OLIVE", "BACON", "ONION", "PEPPER"]],
    ["Shakespeare plays", ["HAMLET", "MACBETH", "OTHELLO", "TEMPEST"]],
    ["Sneaker brands", ["NIKE", "PUMA", "VANS", "REEBOK"]],
    ["Apple products", ["MAC", "IPAD", "WATCH", "AIRPODS"]],
  ],
  [
    ["School subjects", ["MATH", "HISTORY", "ART", "MUSIC"]],
    ["Zodiac signs", ["LEO", "ARIES", "LIBRA", "VIRGO"]],
    ["Streaming services", ["NETFLIX", "HULU", "PEACOCK", "MAX"]],
    ["Kitchen tools", ["WHISK", "LADLE", "SPATULA", "GRATER"]],
  ],
  [
    ["Sports", ["GOLF", "TENNIS", "RUGBY", "POLO"]],
    ["Car brands", ["FORD", "AUDI", "KIA", "TESLA"]],
    ["Seen in the sky", ["SUN", "MOON", "STAR", "CLOUD"]],
    ["___print", ["BLUE", "FOOT", "FINGER", "PAW"]],
  ],
  [
    ["Metals", ["GOLD", "IRON", "TIN", "COPPER"]],
    ["Cooking methods", ["BAKE", "FRY", "GRILL", "ROAST"]],
    ["Desserts", ["PIE", "CAKE", "TART", "FLAN"]],
    ["Golden ___", ["GATE", "RETRIEVER", "RATIO", "HOUR"]],
  ],
  [
    ["Fast food chains", ["SUBWAY", "CHIPOTLE", "POPEYES", "SONIC"]],
    ["Public transit", ["BUS", "TRAM", "FERRY", "METRO"]],
    ["At the beach", ["SAND", "SHELL", "WAVE", "TOWEL"]],
    ["___fall", ["WATER", "NIGHT", "RAIN", "FREE"]],
  ],
  [
    ["Instruments", ["DRUM", "HARP", "FLUTE", "CELLO"]],
    ["Greek letters", ["ALPHA", "BETA", "DELTA", "OMEGA"]],
    ["Halloween", ["GHOST", "WITCH", "PUMPKIN", "BAT"]],
    ["Jackets", ["BOMBER", "DENIM", "PUFFER", "BLAZER"]],
  ],
  [
    ["Ice cream flavors", ["VANILLA", "MINT", "PISTACHIO", "CHERRY"]],
    ["Programming languages", ["PYTHON", "RUBY", "SWIFT", "RUST"]],
    ["Things you can crack", ["CODE", "EGG", "JOKE", "KNUCKLE"]],
    ["One-name pop stars", ["DRAKE", "ADELE", "RIHANNA", "BEYONCE"]],
  ],
  [
    ["In a wallet", ["CASH", "CARD", "ID", "RECEIPT"]],
    ["Poker hands", ["FLUSH", "PAIR", "STRAIGHT", "TRIPS"]],
    ["Inside Out emotions", ["JOY", "FEAR", "ANGER", "DISGUST"]],
    ["___way", ["HIGH", "SUB", "DRIVE", "RUN"]],
  ],
  [
    ["Breakfast foods", ["BAGEL", "WAFFLE", "OMELET", "CEREAL"]],
    ["NBA teams", ["HEAT", "JAZZ", "MAGIC", "THUNDER"]],
    ["Sticky things", ["GLUE", "TAPE", "HONEY", "GUM"]],
    ["___ball", ["FIRE", "PIN", "MEAT", "ODD"]],
  ],
  [
    ["Parts of a story", ["PLOT", "THEME", "SETTING", "CLIMAX"]],
    ["Landforms", ["HILL", "VALLEY", "PLAIN", "CLIFF"]],
    ["Airplane words", ["WING", "PILOT", "CABIN", "AISLE"]],
    ["Bee sounds & actions", ["BUZZ", "STING", "HUM", "SWARM"]],
  ],
  [
    ["Cheeses", ["BRIE", "FETA", "GOUDA", "SWISS"]],
    ["Fonts", ["ARIAL", "CALIBRI", "GEORGIA", "VERDANA"]],
    ["US states", ["TEXAS", "OHIO", "MAINE", "UTAH"]],
    ["Things you can run", ["MILE", "RACE", "ERRAND", "BUSINESS"]],
  ],
  [
    ["Sea creatures", ["CRAB", "SEAL", "SQUID", "SHARK"]],
    ["Breads", ["RYE", "PITA", "NAAN", "SOURDOUGH"]],
    ["Hairstyles", ["BUN", "BOB", "BRAID", "MULLET"]],
    ["Golf scores", ["PAR", "EAGLE", "BIRDIE", "BOGEY"]],
  ],
  [
    ["Citrus fruits", ["LEMON", "LIME", "ORANGE", "GRAPEFRUIT"]],
    ["Things that are cold", ["ICE", "SNOW", "FREEZER", "WINTER"]],
    ["Web browsers", ["CHROME", "SAFARI", "EDGE", "OPERA"]],
    ["___ blue", ["NAVY", "ROYAL", "SKY", "BABY"]],
  ],
  [
    ["Pets", ["CAT", "DOG", "HAMSTER", "PARROT"]],
    ["Board games", ["CHESS", "RISK", "CLUE", "SORRY"]],
    ["Things with teeth", ["COMB", "SAW", "ZIPPER", "GEAR"]],
    ["Apology words", ["OOPS", "PARDON", "MY BAD", "EXCUSE ME"]],
  ],
  [
    ["Shoes", ["BOOT", "LOAFER", "SANDAL", "CLOG"]],
    ["Car parts", ["TRUNK", "HOOD", "BUMPER", "WIPER"]],
    ["Elephant features", ["TUSK", "EAR", "TAIL", "HIDE"]],
    ["Things you can hail", ["TAXI", "CAB", "HERO", "KING"]],
  ],
  [
    ["Soft drinks", ["COKE", "SPRITE", "FANTA", "PEPSI"]],
    ["Mythical creatures", ["DRAGON", "UNICORN", "GRIFFIN", "PHOENIX"]],
    ["Things in a toolbox", ["HAMMER", "WRENCH", "PLIERS", "LEVEL"]],
    ["Video game consoles", ["SWITCH", "XBOX", "WII", "GAMECUBE"]],
  ],
  [
    ["Birds", ["ROBIN", "EAGLE", "OWL", "CROW"]],
    ["Batman villains", ["JOKER", "PENGUIN", "RIDDLER", "BANE"]],
    ["At a birthday party", ["CAKE", "CANDLE", "BALLOON", "GIFT"]],
    ["Nuts", ["PECAN", "ALMOND", "CASHEW", "WALNUT"]],
  ],
  [
    ["Cereals", ["CHEERIOS", "FROOT LOOPS", "TRIX", "KIX"]],
    ["Rappers", ["EMINEM", "KENDRICK", "NAS", "FUTURE"]],
    ["Seasons", ["SPRING", "SUMMER", "FALL", "WINTER"]],
    ["Things with springs", ["MATTRESS", "TRAMPOLINE", "PEN", "WATCH"]],
  ],
  [
    ["Shapes", ["CIRCLE", "SQUARE", "TRIANGLE", "OVAL"]],
    ["Social media actions", ["LIKE", "SHARE", "POST", "FOLLOW"]],
    ["In a classroom", ["DESK", "CHALK", "GLOBE", "ERASER"]],
    ["___ market", ["STOCK", "FLEA", "BLACK", "SUPER"]],
  ],
  [
    ["Reptiles", ["SNAKE", "LIZARD", "TURTLE", "GECKO"]],
    ["Fruits that are also colors", ["ORANGE", "PEACH", "LIME", "PLUM"]],
    ["Pokémon", ["PIKACHU", "CHARIZARD", "SQUIRTLE", "EEVEE"]],
    ["Texting abbreviations", ["LOL", "BRB", "IDK", "TBH"]],
  ],
  [
    ["Team sports", ["SOCCER", "HOCKEY", "VOLLEYBALL", "BASKETBALL"]],
    ["Disney princesses", ["ARIEL", "BELLE", "JASMINE", "MOANA"]],
    ["Flowers", ["ROSE", "TULIP", "DAISY", "LILY"]],
    ["Sandwiches", ["BLT", "CLUB", "SUB", "WRAP"]],
  ],
  [
    ["Vegetables", ["CARROT", "PEA", "BEAN", "ONION"]],
    ["Pixar movies", ["UP", "CARS", "COCO", "SOUL"]],
    ["Card suits", ["HEARTS", "SPADES", "CLUBS", "DIAMONDS"]],
    ["Baseball positions", ["PITCHER", "CATCHER", "SHORTSTOP", "OUTFIELD"]],
  ],
  [
    ["Instruments", ["GUITAR", "BASS", "PIANO", "VIOLIN"]],
    ["Fish", ["TROUT", "SALMON", "TUNA", "COD"]],
    ["Gym equipment", ["DUMBBELL", "TREADMILL", "BENCH", "MAT"]],
    ["___stand", ["HAND", "BAND", "NEWS", "KICK"]],
  ],
  [
    ["Sundae toppings", ["SPRINKLES", "FUDGE", "CHERRY", "WHIPPED CREAM"]],
    ["In a pencil case", ["PENCIL", "ERASER", "RULER", "SHARPENER"]],
    ["Burger toppings", ["LETTUCE", "TOMATO", "PICKLE", "CHEESE"]],
    ["Round things", ["WHEEL", "COIN", "DONUT", "PIZZA"]],
  ],
  [
    ["Thanksgiving dinner", ["TURKEY", "STUFFING", "GRAVY", "PIE"]],
    ["Countries", ["FRANCE", "SPAIN", "JAPAN", "BRAZIL"]],
    ["___pool", ["CAR", "WHIRL", "DEAD", "GENE"]],
    ["Frozen things", ["ICE", "POPSICLE", "TUNDRA", "ELSA"]],
  ],
  [
    ["Dog commands", ["FETCH", "SIT", "STAY", "ROLL OVER"]],
    ["Tree parts", ["BARK", "ROOT", "LEAF", "TRUNK"]],
    ["Swimming strokes", ["FREESTYLE", "BACKSTROKE", "BUTTERFLY", "BREASTSTROKE"]],
    ["___berry", ["BLUE", "STRAW", "RASP", "BLACK"]],
  ],
  [
    ["Fast food order", ["FRIES", "NUGGETS", "BURGER", "SHAKE"]],
    ["Hogwarts houses", ["GRYFFINDOR", "SLYTHERIN", "HUFFLEPUFF", "RAVENCLAW"]],
    ["Snakes", ["COBRA", "PYTHON", "VIPER", "MAMBA"]],
    ["___shake", ["HAND", "MILK", "EARTH", "HARLEM"]],
  ],
  [
    ["Rainbow colors", ["INDIGO", "VIOLET", "ORANGE", "YELLOW"]],
    ["School day", ["LOCKER", "BELL", "BUS", "HOMEWORK"]],
    ["Hair tools", ["BRUSH", "COMB", "DRYER", "CURLER"]],
    ["___cut", ["HAIR", "SHORT", "BUZZ", "PAPER"]],
  ],
  [
    ["Sports gear", ["BAT", "GLOVE", "HELMET", "PUCK"]],
    ["Roman gods", ["MARS", "JUPITER", "VENUS", "NEPTUNE"]],
    ["Cakes", ["SPONGE", "POUND", "LAYER", "BUNDT"]],
    ["Foods with layers", ["ONION", "LASAGNA", "PARFAIT", "BAKLAVA"]],
  ],
  [
    ["Zoo animals", ["LION", "ZEBRA", "GIRAFFE", "HIPPO"]],
    ["At the movies", ["POPCORN", "TICKET", "TRAILER", "SCREEN"]],
    ["Winter clothes", ["SCARF", "MITTENS", "BEANIE", "PARKA"]],
    ["___shot", ["MOON", "SLING", "HOT", "SNAP"]],
  ],
  [
    ["Bugs", ["ANT", "BEE", "FLY", "MOTH"]],
    ["Move fast", ["DASH", "SPRINT", "BOLT", "RACE"]],
    ["Airport", ["GATE", "TERMINAL", "RUNWAY", "LUGGAGE"]],
    ["___ zone", ["END", "TIME", "COMFORT", "DANGER"]],
  ],
  [
    ["Mexican food", ["TACO", "BURRITO", "NACHOS", "SALSA"]],
    ["Olympic sports", ["DIVING", "FENCING", "ROWING", "ARCHERY"]],
    ["Doctors", ["DENTIST", "SURGEON", "VET", "PEDIATRICIAN"]],
    ["___dog", ["HOT", "BULL", "WATCH", "UNDER"]],
  ],
  [
    ["Trees", ["OAK", "PINE", "MAPLE", "BIRCH"]],
    ["In a bedroom", ["BED", "PILLOW", "LAMP", "DRESSER"]],
    ["Bowling", ["STRIKE", "SPARE", "GUTTER", "LANE"]],
    ["___light", ["FLASH", "SPOT", "MOON", "HEAD"]],
  ],
  [
    ["Face parts", ["NOSE", "CHIN", "BROW", "LIP"]],
    ["Winter Olympics", ["SKI", "LUGE", "CURLING", "HOCKEY"]],
    ["Things you hit", ["JACKPOT", "SNOOZE", "GYM", "ROAD"]],
    ["___stick", ["CHOP", "DRUM", "JOY", "YARD"]],
  ],
  [
    ["Kitchen appliances", ["OVEN", "TOASTER", "BLENDER", "MICROWAVE"]],
    ["Cartoon ducks", ["DONALD", "DAFFY", "HOWARD", "SCROOGE"]],
    ["Things with wings", ["PLANE", "BIRD", "BAT", "ANGEL"]],
    ["___house", ["LIGHT", "GREEN", "WARE", "PENT"]],
  ],
  [
    ["Recess games", ["TAG", "DODGEBALL", "KICKBALL", "HOPSCOTCH"]],
    ["Cat breeds", ["TABBY", "SIAMESE", "PERSIAN", "SPHYNX"]],
    ["Music terms", ["TEMPO", "BEAT", "NOTE", "CHORD"]],
    ["___line", ["DEAD", "HEAD", "OUT", "PUNCH"]],
  ],
  [
    ["Mario characters", ["MARIO", "LUIGI", "PEACH", "BOWSER"]],
    ["Fruits", ["GRAPE", "MELON", "BANANA", "APRICOT"]],
    ["Wind & rain", ["BREEZE", "GUST", "STORM", "DRIZZLE"]],
    ["___storm", ["BRAIN", "SAND", "FIRE", "SNOW"]],
  ],
  [
    ["Night sky", ["MOON", "STAR", "COMET", "PLANET"]],
    ["Dr. Seuss characters", ["GRINCH", "LORAX", "HORTON", "THING"]],
    ["Chocolate brands", ["HERSHEY", "KITKAT", "REESES", "GODIVA"]],
    ["Types of rice", ["BROWN", "WILD", "JASMINE", "BASMATI"]],
  ],
  [
    ["Camping", ["TENT", "CAMPFIRE", "LANTERN", "SLEEPING BAG"]],
    ["Yoga poses", ["COBRA", "TREE", "WARRIOR", "PLANK"]],
    ["Things you pitch", ["IDEA", "BALL", "VOICE", "FIT"]],
    ["Superman", ["KRYPTON", "CAPE", "CLARK", "LOIS"]],
  ],
  [
    ["Drinks", ["TEA", "JUICE", "MILK", "WATER"]],
    ["Golf clubs", ["DRIVER", "IRON", "WEDGE", "PUTTER"]],
    ["Bike parts", ["PEDAL", "CHAIN", "SADDLE", "SPOKE"]],
    ["Things you shake", ["MARACA", "SNOW GLOBE", "POLAROID", "MARTINI"]],
  ],
  [
    ["Halloween candy", ["SKITTLES", "REESES", "TWIZZLERS", "NERDS"]],
    ["Greek gods", ["ZEUS", "HERA", "ARES", "APOLLO"]],
    ["Big cats", ["TIGER", "LEOPARD", "JAGUAR", "COUGAR"]],
    ["Pasta", ["PENNE", "ZITI", "ORZO", "FUSILLI"]],
  ],
  [
    ["Money slang", ["DOUGH", "BUCKS", "BREAD", "CHEDDAR"]],
    ["NBA teams", ["LAKERS", "CELTICS", "BULLS", "KNICKS"]],
    ["Cheeses", ["GOUDA", "BRIE", "FETA", "SWISS"]],
    ["Condiments", ["RANCH", "KETCHUP", "MAYO", "MUSTARD"]],
  ],
  [
    ["Christmas", ["SANTA", "ELF", "REINDEER", "STOCKING"]],
    ["Dinosaurs", ["T-REX", "RAPTOR", "STEGOSAURUS", "TRICERATOPS"]],
    ["Basketball plays", ["DUNK", "LAYUP", "REBOUND", "ASSIST"]],
    ["___ship", ["FRIEND", "SPACE", "RELATION", "CHAMPION"]],
  ],
  [
    ["Ocean", ["REEF", "KELP", "CORAL", "TIDE"]],
    ["Laundry", ["DETERGENT", "DRYER", "HAMPER", "BLEACH"]],
    ["Musicals", ["CATS", "WICKED", "HAMILTON", "GREASE"]],
    ["___coat", ["RAIN", "OVER", "TURN", "TOP"]],
  ],
  [
    ["Garden tools", ["HOSE", "SHOVEL", "SEED", "RAKE"]],
    ["Mario Kart items", ["BANANA", "SHELL", "STAR", "MUSHROOM"]],
    ["Wedding", ["RING", "VOWS", "BOUQUET", "AISLE"]],
    ["___case", ["SUIT", "BOOK", "STAIR", "BRIEF"]],
  ],
  [
    ["Feelings", ["HAPPY", "SAD", "MAD", "SCARED"]],
    ["Seven Dwarfs", ["DOC", "GRUMPY", "SLEEPY", "BASHFUL"]],
    ["Things with buttons", ["SHIRT", "REMOTE", "ELEVATOR", "COAT"]],
    ["___cast", ["POD", "FORE", "BROAD", "OVER"]],
  ],
  [
    ["Things that fly", ["KITE", "PLANE", "DRONE", "JET"]],
    ["Sushi", ["TUNA", "SALMON", "EEL", "ROLL"]],
    ["Fire", ["FLAME", "SMOKE", "ASH", "EMBER"]],
    ["___roll", ["EGG", "DRUM", "PAY", "HONOR"]],
  ],
  [
    ["Fast animals", ["CHEETAH", "FALCON", "HARE", "GREYHOUND"]],
    ["Carnival", ["FERRIS WHEEL", "COTTON CANDY", "CLOWN", "RIDE"]],
    ["Sizes", ["SMALL", "MEDIUM", "LARGE", "JUMBO"]],
    ["___paper", ["NEWS", "WALL", "SAND", "TOILET"]],
  ],
  [
    ["Pancake toppings", ["SYRUP", "BUTTER", "BERRIES", "NUTELLA"]],
    ["In a band", ["DRUMS", "BASS", "GUITAR", "KEYS"]],
    ["US presidents", ["LINCOLN", "WASHINGTON", "KENNEDY", "OBAMA"]],
    ["Sleepover", ["PILLOW FIGHT", "MOVIE", "POPCORN", "TRUTH OR DARE"]],
  ],
  [
    ["Toys", ["LEGO", "YOYO", "SLINKY", "DOLL"]],
    ["Things that bounce", ["BALL", "KANGAROO", "TRAMPOLINE", "CHECK"]],
    ["Ways to cook eggs", ["SCRAMBLED", "POACHED", "FRIED", "BOILED"]],
    ["___mate", ["ROOM", "CLASS", "TEAM", "SOUL"]],
  ],
  [
    ["Fruits with pits", ["PEACH", "CHERRY", "PLUM", "MANGO"]],
    ["Star Wars", ["YODA", "VADER", "LEIA", "CHEWIE"]],
    ["Board game pieces", ["DICE", "TOKEN", "CARD", "SPINNER"]],
    ["___root", ["BEET", "SQUARE", "GRASS", "TAP"]],
  ],
  [
    ["At the pool", ["FLOAT", "GOGGLES", "NOODLE", "LADDER"]],
    ["Rap terms", ["BEAT", "FLOW", "BARS", "HOOK"]],
    ["Fishing gear", ["ROD", "REEL", "BAIT", "LURE"]],
    ["___boat", ["SAIL", "ROW", "TUG", "SPEED"]],
  ],
  [
    ["Spices", ["PEPPER", "CUMIN", "PAPRIKA", "GINGER"]],
    ["Cookies", ["OREO", "SNICKERDOODLE", "MACARON", "BISCOTTI"]],
    ["Car types", ["SEDAN", "COUPE", "HATCHBACK", "MINIVAN"]],
    ["___bread", ["CORN", "SHORT", "FLAT", "SWEET"]],
  ],
  [
    ["Ice sports", ["HOCKEY", "CURLING", "LUGE", "BOBSLED"]],
    ["In space", ["ASTEROID", "COMET", "GALAXY", "NEBULA"]],
    ["Coffee shop", ["BARISTA", "MUG", "BEANS", "FOAM"]],
    ["___ trip", ["ROAD", "FIELD", "GUILT", "ROUND"]],
  ],
  [
    ["Sweet things", ["CANDY", "HONEY", "SUGAR", "SYRUP"]],
    ["Terms of endearment", ["BABE", "DEAR", "SWEETIE", "DARLING"]],
    ["___ truck", ["PICKUP", "DUMP", "TOW", "FIRE"]],
    ["___fly", ["BUTTER", "DRAGON", "HOUSE", "BAR"]],
  ],
  [
    ["Crops", ["WHEAT", "CORN", "RICE", "SOY"]],
    ["Skateboard tricks", ["OLLIE", "KICKFLIP", "GRIND", "SHUVIT"]],
    ["Movie genres", ["HORROR", "COMEDY", "DRAMA", "ACTION"]],
    ["___corn", ["POP", "UNI", "PEPPER", "CANDY"]],
  ],
];
